<?php

namespace SOSBundle\Repository;

/**
 * AnimalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimalRepository extends \Doctrine\ORM\EntityRepository
{
    public function recherche($valeur){
        $query = AnimalRepository::createQueryBuilder('r')
            ->where('UPPER(r.espece) LIKE UPPER(:valeur)')
            ->orWhere('UPPER(r.race) LIKE UPPER(:valeur)')
            ->orWhere('UPPER(r.sexe) LIKE UPPER(:valeur)')
            ->orWhere('UPPER(r.taille) LIKE UPPER(:valeur)')
            ->orWhere('UPPER(r.description) LIKE UPPER(:valeur)')
            ->orWhere('UPPER(r.type) LIKE UPPER(:valeur)')
            ->setParameter('valeur','%'.$valeur.'%')
            ->getQuery();

        return $query->getResult();
    }
}
