<?php

namespace EcommerceBundle\Repository;

/**
 * LivreurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivreurRepository extends \Doctrine\ORM\EntityRepository
{
    public function findRegionDQL($nom){
        $query= $this->getEntityManager()
            ->createQuery("select m from EcommerceBundle:Livreur m where m.region=:N")->setParameter('N',$nom);
        return $query->getResult();
    }
}
