<?php

namespace Animaux1Bundle\Repository;

/**
 * CommentaireVetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireVetRepository extends \Doctrine\ORM\EntityRepository
{
}
