<?php

namespace Animaux1Bundle\Repository;

/**
 * MailVetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailVetRepository extends \Doctrine\ORM\EntityRepository
{
}
