<?php

namespace Animaux1Bundle\Repository;

/**
 * ProfilAnimalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfilAnimalRepository extends \Doctrine\ORM\EntityRepository
{
}
