<?php

namespace Animaux1Bundle\Repository;

/**
 * ReclamationVetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReclamationVetRepository extends \Doctrine\ORM\EntityRepository
{
}
