<?php

namespace Animaux1Bundle\Repository;

/**
 * VetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VetRepository extends \Doctrine\ORM\EntityRepository
{
}
