<?php

namespace BienetreBundle\Repository;

/**
 * CommentaireEvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireEvenementRepository extends \Doctrine\ORM\EntityRepository
{public function getCommentsForBlog($a)
{
    $qb = $this->createQueryBuilder('c')
        ->select('c')
        ->where('c.EvenementA = :ss')
        ->addOrderBy('c.dateCommentaire')
        ->setParameter('ss', $a);



    return $qb->getQuery()
        ->getResult();
}
}
