<?php

namespace BienetreBundle\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * ParticipantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipantRepository extends \Doctrine\ORM\EntityRepository
{


    public function getComments($userc,$evenement){
        $qb = $this->createQueryBuilder('v');

        $qb->where('v.user  = :user')
            ->andWhere('v.evenement = :evenement')
            ->setParameter('user', $userc)

            ->setParameter('evenement', $evenement);


        $result = $qb->getQuery()
            ->getResult();
        return $result;

}}
