<?php

namespace BoutiqueBundle\Repository;

/**
 * ReclamationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReclamationRepository extends \Doctrine\ORM\EntityRepository
{
    function recherche($valeur){
        $query = ReclamationRepository::createQueryBuilder('r')
            ->where('UPPER(r.subject) LIKE UPPER(:valeur)')
            ->orWhere('UPPER(r.mobile) LIKE UPPER(:valeur)')
            ->orWhere('UPPER(r.email) LIKE UPPER(:valeur)')
            ->orWhere('UPPER(r.titre) LIKE UPPER(:valeur)')
            ->orWhere('UPPER(r.nom) LIKE UPPER(:valeur)')
            ->orWhere('UPPER(r.mobile) LIKE UPPER(:valeur)')

            ->setParameter('valeur','%'.$valeur.'%')
            ->getQuery();

        return $query->getResult();
    }


    function char()
    {

        $query= $this->getEntityManager()
            ->createQuery("SELECT COUNT(*) AS id FROM reclamation Group By email");
        return $query->getResult();
        //$counter=mysql_query("SELECT COUNT(*) AS id FROM discussion Group By titre");
    }
}
